version: "3.8"
name: saude-solidaria

services:
  flask-server:
    container_name: flask-server
    build:
      context: ..
      dockerfile: build/Dockerfile
    ports:
      - 8888:5000
    volumes:
      - ../.env:/app/.env
      - ../logs:/app/logs
    env_file:
      - ../.env
    depends_on:
      - local-db # Altere a dependência para o novo serviço

  db:
    container_name: postgresql
    image: postgres:16.3-bookworm
    restart: always
    env_file:
      - ../.env
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -h db"
      interval: 3s
      timeout: 5s
      retries: 5

  local-db:
    container_name: local-postgresql
    image: postgres:16.3-bookworm
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: saude_solidaria
    ports:
      - "5433:5432" # Mapeia a porta 5432 do container para 5433 no host
    volumes:
      - local_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -h localhost"
      interval: 3s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ../.env
    ports:
      - 15432:80
    depends_on:
      - local-db # Altere a dependência para o novo serviço
    volumes:
      - pgadmin:/var/lib/pgadmin

volumes:
  pgdata:
  local_pgdata:
  pgadmin:
